### ISSUE TITLE
[Bug] No syncing with other plugins. Currency not working

### ISSUE THREAD

**Issue by ramazansancar** [ArdaGnsrn/steam-try-chrome#1]
Currency translation is not working correctly.
Activate Extension:
![image](https://github.com/ArdaGnsrn/steam-try-chrome/assets/8878055/9e01ff97-391a-46c4-a6b9-21c687e758ca)

Passive Extension:
![image](https://github.com/ArdaGnsrn/steam-try-chrome/assets/8878055/0adc26fc-4ae3-4bb4-ac77-922c76431a21)

Other Gaming Extensions:
- [alike03's Subscription Info on Steam](https://chromewebstore.google.com/detail/jecikjbpiedagpmibmgpfgnkfpomgeok)
- [Augmented Steam](https://chromewebstore.google.com/detail/dnhpnfgdlenaccegplpojghhmaamnnfp)
- [Instant Gaming](https://chromewebstore.google.com/detail/lbnoedlobifdhbpjkcfhcbdcjhampmne)

Solution:
Add:
- ".game_purchase_price .price"

**Comment by ArdaGnsrn** [comment]
Thanks for your support. I will update extension on Chrome Web Store ASAP.

**Comment by ramazansancar** [comment]
Here I realized that something else was affecting the problem. @ArdaGnsrn 

Solution:
https://github.com/ArdaGnsrn/steam-try-chrome/blob/master/content-script.js#L38
```css
.steam-try {
    font-size: 13px !important;
}
 ```

![image](https://github.com/ArdaGnsrn/steam-try-chrome/assets/8878055/776903e5-103a-4f6c-9640-ecd85bb3cf46)

![chrome_UZatB7dyUy](https://github.com/ArdaGnsrn/steam-try-chrome/assets/8878055/c4430c54-8253-41a2-8d81-6b5323965b40)


Solution After:
![chrome_dYjk7NsBSV](https://github.com/ArdaGnsrn/steam-try-chrome/assets/8878055/3eecedb3-cf9c-4c57-92a2-08b52bf327df)
